### ISSUE TITLE
Class 'cronmanager' not found

### ISSUE THREAD

**Issue by a5hma5h** [POSSA/freepbx-trunk-balancing#35]
Hello! After install, when i try to open "Trunk Balance" in FreePBX menu,  i get an error:
 Whoops \ Exception \ ErrorException (E_ERROR)
Class 'cronmanager' not found

/var/www/html/admin/modules/trunkbalance/page.trunkbalance.php:78
This string in file:
    // check to see if user has automatic updates enabled
    $cm =& cronmanager::create($db);
    $online_updates = $cm->updates_enabled() ? true : false;
   
How can i fix this?

**Comment by lgaetz** [comment]
Try installing new ver. 1.1.4, it's been updated to work with FreePBX 14

**Comment by a5hma5h** [comment]
Thank you! You're brilliant!

**Comment by a5hma5h** [comment]
> Try installing new ver. 1.1.4, it's been updated to work with FreePBX 14

It's solved. Thank you! You're brilliant!
